### ISSUE TITLE
`lualina_b` and `lualine_c` have same color

### ISSUE THREAD

**Issue by chrisgrieser** [HoNamDuong/hybrid.nvim#1]
Thanks for the theme, saw it on reddit and love it.

I minor issue I noted is that the inner lualine sections (`lualina_b` and `lualine_c`) seem to have the same color. (Same with `lualina_x` and `lualine_y`.)  The demo screenshot in the README also looks like it. 

I find them having at least slightly different colors useful for finding stuff in a crammed status line like mine. Could those color differentiation maybe be added? 🙏

**Comment by HoNamDuong** [comment]
Here is an example that helps you customize lualine with hybrid theme:

```lua
local c = require("hybrid.colors").setup()

local hybrid_theme = {
    normal = {
        a = { bg = c.blue, fg = c.bg },
        b = { bg = c.line, fg = c.blue },
        c = { bg = c.line, fg = c.fg },
    },
    insert = {
        a = { bg = c.green, fg = c.bg },
        b = { bg = c.line, fg = c.green },
    },
    visual = {
        a = { bg = c.magenta, fg = c.bg },
        b = { bg = c.line, fg = c.magenta },
    },
    replace = {
        a = { bg = c.red, fg = c.bg },
        b = { bg = c.line, fg = c.red },
    },
    command = {
        a = { bg = c.yellow, fg = c.bg },
        b = { bg = c.line, fg = c.yellow },
    },
    inactive = {
        a = { bg = c.bg, fg = c.fg },
        b = { bg = c.bg, fg = c.fg },
        c = { bg = c.bg, fg = c.fg },
    },
}

require("lualine").setup({
    options = { theme = hybrid_theme },
})
```

**Comment by chrisgrieser** [comment]
thx for the quick response!

However, I personally think that this is not a customization question. The whole purpose of statusline sections is to group components via background color, they serve no other purpose other than that. 

If any user wants all their statusline components to have the same background color, they'd put them all into `lualine_b`, instead of splitting across `lualine_b` and `lualine_c`. By coloring`lualina_b` and`lualine_c` the same, the color scheme effectively disables a statusline feature by default, which I'd consider a bug.

**Comment by HoNamDuong** [comment]
Ok, I get it now, I will change them in the next commit.
