### ISSUE TITLE
fields & strings are not differentiated

### ISSUE THREAD

**Issue by chrisgrieser** [HoNamDuong/hybrid.nvim#2]
I noticed that fields and strings both get the same green tone in this color scheme. This results in almost the whole text being one color:
![Pasted image 2024-01-01 at 16 23 19@2x](https://github.com/HoNamDuong/hybrid.nvim/assets/73286100/cc3c6e36-835f-4228-af11-ffc35a4ac20a)

for comparison, here is how it looks in a different theme, where fields and strings have different colors
![Pasted image 2024-01-01 at 16 26 39@2x](https://github.com/HoNamDuong/hybrid.nvim/assets/73286100/a52c3685-c3f9-4b25-96c3-06ef38c9c43e)

This issue is not restricted to lua, the same happens in for instance in yaml:
![Pasted image 2024-01-01 at 16 22 56@2x](https://github.com/HoNamDuong/hybrid.nvim/assets/73286100/bbfea5fa-9b52-4150-8690-0c718ac14221)

**Comment by HoNamDuong** [comment]
Sorry, I still don't have ideas for syntax highlights.
I copied them from Tokyo theme.
I'm going to change the color of a few things.
