### ISSUE TITLE
Markdown highlights

### ISSUE THREAD

**Issue by bleacheda** [HoNamDuong/hybrid.nvim#4]
Hello,

To start off, thanks for the theme, absolutely love it.

A few ideas/suggestions for markdown highlights:

1. make bold text also a different color than normal text
2. make unordered lists markers: dashes (-), asterisks (*), or plus signs (+) a different color than normal text
3. make ordered lists markers (1. 2. 3. etc.) a different color than normal text
4. make angle brackets links a different color than normal text

comparison for reference (hybrid left  - nightfox right)

![image](https://github.com/HoNamDuong/hybrid.nvim/assets/60625523/55ce4ac5-fa31-477f-a3b0-d9af901b85cf)

**Comment by HoNamDuong** [comment]
Thank you, I will add them in the next commit.

**Comment by bleacheda** [comment]
Thanks!
I hope it is ok if I add other possible suggestions related to Markdown here

- make different level headings different colors

comparison for reference (hybrid left - tokyonight right)

![image](https://github.com/HoNamDuong/hybrid.nvim/assets/60625523/3f6c36b1-a435-4d91-b7a8-0fe353ac43ce)

**Comment by bleacheda** [comment]
I've just updated with the latest commit, awesome that you added so many options so fast.

- list markers and headings are very nice
- the new background for code blocks is interesting

Could you please provide examples on how to override all the markdown highlights options? I tried to follow the example in the README but didn't manage to adapt it for markdown.

**Comment by HoNamDuong** [comment]
> Could you please provide examples on how to override all the markdown highlights options? I tried to follow the example in the README but didn't manage to adapt it for markdown.

Example:
```lua
require("hybrid").setup({
    overrides = function(hl, c)
        hl["@markup.strong"] = { bold = true }
        hl["@markup.italic"] = { italic = true }
        hl["@markup.strikethrough"] = { strikethrough = true }
        hl["@markup.underline"] = { underline = true }
        hl["@markup.heading"] = { link = "Title", bold = true }
        hl["@markup.heading.1"] = { fg = c.bright_yellow, bold = true }
        hl["@markup.heading.2"] = { fg = c.bright_green, bold = true }
        hl["@markup.heading.3"] = { fg = c.bright_cyan, bold = true }
        hl["@markup.heading.4"] = { fg = c.yellow }
        hl["@markup.heading.5"] = { fg = c.green }
        hl["@markup.heading.6"] = { fg = c.cyan }
        hl["@markup.quote"] = { fg = c.blue }
        hl["@markup.math"] = { fg = c.magenta }
        hl["@markup.list"] = { fg = c.blue }
        hl["@markup.list.checked"] = { fg = c.green }
        hl["@markup.list.unchecked"] = { fg = c.blue }
        hl["@markup.link"] = { fg = c.magenta }
        hl["@markup.link.label"] = { fg = c.bright_blue }
        hl["@markup.link.url"] = { fg = c.cyan, underline = true }
        hl["@markup.raw"] = { bg = c.bg_soft }
        hl["@markup.raw.block"] = { bg = c.bg_soft, fg = c.green }
    end,
})
```

**Comment by bleacheda** [comment]
Ah, I was trying it with `hl.[` and also couldn't figure out the `opts` part in `highlights.lua`.
Awesome, thanks.
